name: Deploy MDBook
description: Easily build and deploy your mdbook projects onto github pages.
branding:
  icon: book
  color: blue
inputs:
  branch:
    description: The branch to deploy to.
    default: gh-pages
  repository:
    description: The github reposistory in `owner/repo` format.
    required: true
  build_only:
    description: Disable deployment.
  workspace:
    description: The working directory for the action. Default $GITHUB_WORKSPACE
  token:
    description: The GitHub token for deploying mdbook.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
