name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - run: git clone https://github.com/rust-lang/book.git /tmp/book
        - uses: ./
          env:
            DEBUG_DEPLOY_ACTION: 1
          with:
            workspace: /tmp/book
            branch: ci-book
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: rust-lang/project-group-template
